# Generated by Django 2.1.3 on 2018-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(default='Disponible', max_length=255)),
                ('imageUrl', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
