# Generated by Django 2.1.3 on 2018-11-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_mascota', models.ImageField(blank=True, null=True, upload_to='perros/%Y/%m/%D/')),
                ('nombre_mascota', models.CharField(max_length=15)),
                ('raza_mascota', models.CharField(max_length=30)),
                ('descripcion_mascota', models.TextField()),
                ('estado_mascota', models.CharField(choices=[('rescatado', 'Rescatado'), ('disponible', 'Disponible'), ('adoptado', 'Adoptado')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Perros',
        ),
    ]
